Feat/auto db
saraTag/Dauphine-Pole-Info pull request #12
Opened 2019-01-16 15:12 UTC by saraTag

Fonctionnalité : AutoBD

2019-01-16 15:55 UTC, oliviercailloux requested changes
Veuillez mettre à jour le badge Travis dans le README, pour qu’on puisse admirer le résultat.

2019-01-16 16:06 UTC, oliviercailloux commented
Le fichier de cahier des charges doit s’appeler README.adoc, à moins que vous ayez une raison particulière pour le renommer qui m’aurait échappé ? (Vous pouvez le renommer dans cette branche.)

2019-01-16 16:49 UTC, saraTag commented
Le readme que je déjà fusionné au master est nommé "README-sara" car on a gardé l'ancien "REDME" du groupe de l'année passée

2019-01-16 17:03 UTC, saraTag commented
Si je renomme dans cette branche je vais écraser le contenu du README du master (ancien README) au moment de la fusion  ?

2019-01-16 17:51 UTC, oliviercailloux commented
Votre nouveau fichier reprend je crois déjà le contenu ancien ! (Si non, il faut l’y mettre.)
Je vous laisse vous débrouiller comme vous voulez pour que votre README se retrouve correctement dans la branche master.

2019-01-17 09:58 UTC, saraTag commented
Notre README est bien mis jour dans la branche master ( j'ai repris l'ancien contenu et j'ai ajouté notre cahier de charges )

2019-01-22 10:30 UTC, oliviercailloux approved these changes

2019-01-30 09:59 UTC, merged