Basics
saraTag/Dauphine-Pole-Info pull request #17
Opened 2019-02-18 17:14 UTC by thejoker2323

ajouter les classes nécessaires pour mettre en confirmité le modéle de classe et celui de données ( schema.sql )

2019-02-19 12:36 UTC, oliviercailloux requested changes
Il faut sans-doute revoir la partie JPA du cours, pour mettre en œuvre ce qui a été enseigné.

2019-02-19 12:36 UTC, oliviercailloux commented on README-2017.adoc
> += Dauphine Pole Info
La version 2017 du README est stockée dans l’historique git. C’est à ça qu’il sert. Conservez simplement les informations utiles de ce README dans le nouveau, s’il y a qqch. qui vous semble utile. Peut-être les instructions d’installation ? Il faut conserver les noms des anciens contributeurs également.

2019-02-19 12:36 UTC, oliviercailloux commented on pom.xml
> +			<groupId>mysql</groupId>
Non, il faut indépendance par rapport au connecteur. La connexion est à configurer côté serveur uniquement.

2019-02-19 12:36 UTC, oliviercailloux commented on pom.xml
> +			<version>3.20.0-GA</version>
Une version de 2015, vraiment ?

2019-02-19 12:36 UTC, oliviercailloux commented on pom.xml
> +			<artifactId>slf4j-log4j12</artifactId>
Non, log4j est nécessaire seulement au runtime (c’est un "binding"). Voir doc SLF4J. Ou utilisez simplement JUL comme vu au cours.

2019-02-19 12:36 UTC, oliviercailloux commented on pom.xml
> +			<groupId>org.hibernate</groupId>
Non, vous devez être indépendant d’hibernate.

2019-02-19 12:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/ServletContent.java
> +	private static final EntityManagerFactory ENTITY_MANAGER_FACTORY = Persistence
Profiter de la gestion automatique par votre conteneur, comme indiqué à la fin des exercices JPA.

2019-02-19 12:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/ServletContent.java
> +            ex.printStackTrace();
Sûrement pas. Il ne faut pas masquer l’exception mais la propager.

2019-02-19 12:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/ServletPerson.java
> +    public static void setPerson(int id, String firstname,String lastname, String email,String phone, String fax, String home_page, String cv, String note, String role, String password, String addres
Éviter des méthodes avec d’aussi nombreux paramètres, surtout quand ils sont de même types. Vos objets devraient aussi servir à ça.

2019-02-19 12:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/ServletPerson.java
> +    public static void setPerson(int id, String firstname,String lastname) {
Une seule méthode plus générale serait suffisante.

2019-02-19 12:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/ServletPerson.java
> +		create(1,"lahsen","jannani","","","","","","","","","","","");
Ce n’est pas ce qui est demandé ni attendu d’un GET.

2019-02-19 12:36 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +			<property name="javax.persistence.jdbc.driver" value="com.mysql.jdbc.Driver" />
Non, configurer au niveau du serveur.

2019-02-19 14:56 UTC, thejoker2323 commented on src/main/java/io/github/oliviercailloux/y2018/ServletPerson.java
> +		create(1,"lahsen","jannani","","","","","","","","","","","");
cette classe ne fait pas partie de ma fonctionnalité ( basics )

2019-02-19 14:56 UTC, thejoker2323 commented on src/main/java/io/github/oliviercailloux/y2018/ServletPerson.java
> +    public static void setPerson(int id, String firstname,String lastname) {
cette classe ne fait pas partie de ma fonctionnalité ( basics )

2019-02-19 14:56 UTC, thejoker2323 commented on src/main/java/io/github/oliviercailloux/y2018/ServletPerson.java
> +    public static void setPerson(int id, String firstname,String lastname, String email,String phone, String fax, String home_page, String cv, String note, String role, String password, String addres
cette classe ne fait pas partie de ma fonctionnalité ( basics )

2019-02-19 14:56 UTC, thejoker2323 commented on src/main/java/io/github/oliviercailloux/y2018/ServletContent.java
> +            ex.printStackTrace();
cette classe ne fait pas partie de ma fonctionnalité ( basics )

2019-02-19 14:57 UTC, thejoker2323 commented on src/main/java/io/github/oliviercailloux/y2018/ServletContent.java
> +            ex.printStackTrace();
cette classe ne fait pas partie de ma fonctionnalité ( basics )

2019-02-19 15:01 UTC, thejoker2323 commented on README-2017.adoc
> += Dauphine Pole Info
c'est ce qu'on a fait , on a repris les nom des anciens contributeurs  , en plus des instructions d’installation , puis on a ajouté notre README ,

2019-02-19 15:42 UTC, thejoker2323 commented on pom.xml
> +			<version>3.20.0-GA</version>
était présent sur le fichier pom.xml de départ

2019-02-19 15:42 UTC, thejoker2323 commented on pom.xml
> +			<groupId>mysql</groupId>
était présent sur le fichier pom.xml de départ

2019-02-19 15:42 UTC, thejoker2323 commented on pom.xml
> +			<artifactId>slf4j-log4j12</artifactId>
était présent sur le fichier pom.xml de départ

2019-02-19 15:42 UTC, thejoker2323 commented on pom.xml
> +			<groupId>org.hibernate</groupId>
était présent sur le fichier pom.xml de départ

2019-02-19 20:23 UTC, oliviercailloux commented on README-2017.adoc
> += Dauphine Pole Info
Il faut tout dans le même README.

2019-02-19 20:23 UTC, oliviercailloux commented on pom.xml
> +			<groupId>mysql</groupId>
Votre mission est d’améliorer l’existant.

2019-02-19 20:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/ServletPerson.java
> +    public static void setPerson(int id, String firstname,String lastname) {
Dans ce cas il faut indiquer dans le PR les classes concernées, comme demandé oralement en cours.

2019-02-19 20:26 UTC, oliviercailloux commented
Je ferme pour le moment ; rouvrez quand vous souhaitez nouvelle relecture, pour que je sois averti.

2019-02-19 21:12 UTC, thejoker2323 commented
j'ai fait les modifications nécessaires , mis à jour le pom.xml et persistence.xml , enlevé les classes qui sont en dehors de "basics".

2019-02-24 22:45 UTC, oliviercailloux requested changes
Encore des problèmes de configuration de JPA pour indépendance vis-à-vis du fournisseur JPA. Et autres commentaires. Voir review.

2019-02-24 22:45 UTC, oliviercailloux commented on pom.xml
> +			<groupId>org.apache.logging.log4j</groupId>
Vous ne devriez pas avoir besoin de ça, je pense. Veuillez respecter les instructions données en cours concernant les logs, ou indiquer pourquoi vous souhaitez en dévier.

2019-02-24 22:45 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +		<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
Il faut corriger ceci aussi, et ne pas utiliser un Resource_local.

2019-02-24 22:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/Person.java
> +@Table(name = "personne")
En anglais, c’est mieux. Enlever les annotations inutiles, donc (car traduction non désirable).

2019-02-24 22:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/Person.java
> -@JsonbPropertyOrder({ "id", "firstname", "lastname" })
Pourquoi enlever ceci ? Au contraire, c’est utile.

2019-02-24 22:45 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/PersonServletTest.java
> +		String str = "{\"firstname\":\"Tuti\",\"id\":1,\"lastname\":\"Dudi\",\"year_master\":0}";
Il me semble plus attendu d’envoyer l’id d’abord. Et pourquoi pas les autres champs ?

2019-02-25 09:01 UTC, thejoker2323 commented on src/test/java/io/github/oliviercailloux/y2018/PersonServletTest.java
> +		String str = "{\"firstname\":\"Tuti\",\"id\":1,\"lastname\":\"Dudi\",\"year_master\":0}";
c'est la classe de test pour la servlet , qui ne fait pas partie de ma fonctionnalité

2019-02-25 09:10 UTC, thejoker2323 commented on src/main/resources/META-INF/persistence.xml
> +		<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
c'était la configuration initiale du projet d'origine

2019-02-25 09:42 UTC, thejoker2323 commented on pom.xml
> +			<groupId>org.apache.logging.log4j</groupId>
permet de router les log en log4j qui offre plusieurs détails sur le bug et son niveau ( level ) , ce qui facilite et accélére le debuggage par rapport à JUL.

2019-02-25 09:44 UTC, thejoker2323 commented
j'ai procédé aux modifications nécessaires.

2019-02-25 09:48 UTC, thejoker2323 commented
@oliviercailloux  vous pouvez re-voir à nouveau.

2019-02-26 14:23 UTC, oliviercailloux requested changes
Il faut également enlever la dépendance à hibernate dans le pom.

2019-02-26 14:23 UTC, oliviercailloux commented on pom.xml
> +			<groupId>org.apache.logging.log4j</groupId>
Ok, si vous l’utilisez, c’est très bien. Cependant, la consigne demande de discuter de toute déviation par rapport aux standards Java. Je vous prie de plutôt choisir SLF4J, mentionné dans le cours. La migration devrait être simple.

2019-02-26 14:23 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +		<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
Je n’en doute pas. Mais il faut le corriger néanmoins pour se conformer aux pratiques et exigences vues au cours et en particulier éviter des ennuis futurs ou des incompatibilités avec d’autres serveurs d’application.

2019-02-26 14:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/Person.java
> +@Table(name = "personne")
J’imagine que mon commentaire était incorrect, car vous devez vous conformer au schéma existant. Mais une réponse aurait été bienvenue néanmoins.

2019-02-26 15:17 UTC, thejoker2323 commented
voila les nouveaux changements : 
pour le sfl4j ; j'ai choisi une version parmi les plus récentes , et la plus stable , cependant ce n'est pas la derniére , 
pour le provider , j'ai spécifié hibernate , cependant , on est totalement indépendant de l'ORM tant qu'on utilisera que les annotations JPA.
@oliviercailloux

2019-02-26 16:13 UTC, oliviercailloux commented
Veuillez ne pas spécifier Hibernate, pour rendre cette indépendance effective et visible.

2019-02-27 08:03 UTC, thejoker2323 commented
@oliviercailloux  c'est fait

2019-03-01 10:19 UTC, oliviercailloux approved these changes

2019-03-01 10:57 UTC, merged