Basic servlets
saraTag/Dauphine-Pole-Info pull request #18
Opened 2019-02-19 18:55 UTC by jannani-lahsen

2019-02-24 22:49 UTC, oliviercailloux requested changes
De nombreuses modifications sont mentionnées dans votre README. Ça ne parait aucunement lié à votre fct Basic servlets. Veuillez enlever ces modifications, et vérifier que toutes vos modifications sont bien uniquement liées à votre fct.
Il faut bien gérer les exceptions, donc sans les masquer.
Il faut probablement attendre que les objets de base soient finalisés car sinon, il me semble impossible de s’assurer que cette fct fonctionne. Veuillez demander une nouvelle review quand c’est fait et que vous avez corrigé au moins les points ci-dessus.
Changez ceci, et nous verrons ensuite.

2019-02-25 09:24 UTC, jannani-lahsen commented
@oliviercailloux j'ai gardé le meme readme que mes autres collegues (fusion de celui de 2017 et 2018) j'ai ajouté seuelement une ligne pour décrire ma deuxieme fonctionnalité du sprint 2 (fonctionnalité Repr : pouvoir encoder et décoder en json les objets)

2019-02-25 09:39 UTC, jannani-lahsen commented
@oliviercailloux en ce qui concerne les modifications que j'avais fait, j'ai modifié les classes person et content, pour respecter les standards JPA, et j'ai créer personservlet et contentservlet ( CRUD pour person et content) ainsi que l'ajout du fichier persistence.xml

2019-02-26 14:31 UTC, oliviercailloux commented
Résoudre conflit avant ma review.
Votre fct a de nombreux points communs avec #17 . Il va falloir attendre la validation de #17 avant de pouvoir discuter de votre fct.
Rouvrez quand c’est fait.

2019-03-01 14:16 UTC, jannani-lahsen commented
@oliviercailloux  #17 est désormais valider, pourriez vous m'adresser les changements à faire ? merci

2019-03-01 14:18 UTC, jannani-lahsen commented
@oliviercailloux #17 est désormais valider, pourriez vous m'adresser les changements à faire ? merci

2019-03-04 10:59 UTC, oliviercailloux commented
This branch has conflicts that must be resolved.

2019-03-04 13:55 UTC, jannani-lahsen commented
@oliviercailloux C'est fait pour tous les classes sauf pour Person.java, en effet sans faute de ma part il me semble que le code de la classe parson.java n'est pas bon, par exemple (@Table(name = "person") la table person n'existe pas en se référant au fichier Schema.sql, de meme la table n'a pas de champs firstname and lastname mais plutot nom prenom (en se référant au fichier Schema.sql) c'est ce que j'avais corrigé moi pour la classe person.java
merci

2019-03-04 15:12 UTC, oliviercailloux commented
C’est une faute de votre part que des conflits existent. Je vous prie de les résoudre avant de soumettre votre demande de review. Voir exercices sur git du cours pour comprendre les concepts et se renseigner sur internet concernant la partie spécifique à GitHub.

2019-03-04 15:39 UTC, jannani-lahsen commented
@oliviercailloux C'est fait monsieur

2019-03-04 15:53 UTC, oliviercailloux commented
Veuillez gérer les exception comme vu au cours (voir aussi BP Exceptions).
Le code ne fait pas ce qu’il devrait faire, pour autant que je puisse voir. Il devrait par exemple offrir un servlet permettant de modifier le prénom d’une personne, selon un choix déterminé par l’utilisateur.

2019-03-11 14:08 UTC, jannani-lahsen commented
@oliviercailloux Pourriez vous voir SVP? CRUD servlet person and content

2019-03-11 15:53 UTC, oliviercailloux commented
À ce stade je propose de s’attarder seulement sur l’erreur la plus importante, à cause du retard accumulé sur la première itération. Il s’agit des exceptions. Elles ne doivent jamais être masquées, mais bien être renvoyées à l’appelant. Par exemple Update ne doit pas renvoyer ok si une exception est survenue. Le plus simple est de simplement renvoyer toute exception hors de la méthode pour que le conteneur la gère.

2019-03-11 17:30 UTC, jannani-lahsen commented
@oliviercailloux  Pouvez vous revoir à nouveau? merci

2019-03-12 13:44 UTC, oliviercailloux commented
C’est mieux en effet. Ok pour la fusion.

2019-03-12 13:44 UTC, oliviercailloux approved these changes

2019-03-12 13:58 UTC, merged