Repr
saraTag/Dauphine-Pole-Info pull request #19
Opened 2019-03-14 19:50 UTC by jannani-lahsen

Pouvoir encoder et décoder en JSON person et content isolément sans les informations de lien entre eux

2019-03-15 11:09 UTC, oliviercailloux commented
Évitez les méthodes avec de très nombreux paramètres, difficiles à lire et encouragent les erreurs. Vos constructeurs énormes ne semblent pas utiles puisque vous avez les setters.
Plutôt qu’encoder le résultat attendu du test en dur dans un String, placez-le dans un fichier dans les ressources du test. Lisez le fichier dans votre test et comparez au résultat de la (dé)-sérialisation.

2019-03-15 22:46 UTC, jannani-lahsen commented
@oliviercailloux Pouver vous revoir le code à nouveau ? merci

2019-03-17 10:49 UTC, oliviercailloux requested changes

2019-03-17 10:49 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/Content.java
> +	public void contenuToJson(Content cont, String url) throws JsonbException, FileNotFoundException {
C’était mieux avant. On doit pouvoir récupérer le contenu au format Json en travaillant uniquement en mémoire, on ne veut pas nécessairement l’écrire dans un fichier. L’ancienne méthode était plus générale. Elle permettait également d’écrire le résultat dans un fichier si c’est ce que l’utilisateur désire, mais pas seulement.

Par ailleurs, la méthode ne doit pas parler à moitié français (contenu n’étant pas un mot anglais à ma connaissance). `toJson()` suffirait.

2019-03-17 10:49 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/Person.java
> +			String cv, String note, String password, String role, String address, String mobile, String temporary) {
Je n’ai pas l’impression que mon commentaire sur les constructeurs aux trop nombreux paramètres ait été pris en compte…

2019-03-17 10:49 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/dauphine_pole_info/TestJsonBEncode.java
> +
Non, il faut encoder la personne en json en mémoire et comparer au contenu du fichier.

2019-03-17 10:49 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/dauphine_pole_info/TestJsonBDecode.java
> +		String url = "src\\test\\resources\\Person.json";
Ce n’est pas une manière élégante de lire vos ressources dans votre class path. Voir BP resources et cours sur class path si nécessaire.

2019-03-17 10:49 UTC, oliviercailloux commented on src/test/resources/Content.json
> +{"id":1,"name":"name","hourlyVolume":356,"etcs":3.0,"projectVolume":4}
Il serait nettement mieux d’afficher ceci en mode « pretty print », pour une meilleure lisibilité. Ce fichier sert en même temps de documentation utile sur le format que vos servlets utilisent.
Voir exemple donné dans le cours sur JSONB pour encodage et décodage pretty print.

2019-03-17 10:49 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/dauphine_pole_info/TestJsonBEncode.java
> +		cont2=cont2.jsonToContenu(url);
Formatter code.

2019-03-18 22:39 UTC, jannani-lahsen commented
@oliviercailloux Est ce que vous pouvez revoir le code svp ? merci

2019-03-20 07:40 UTC, oliviercailloux requested changes
Pourquoi supprimer les deux classes Test de vos collègues ?

2019-03-20 07:40 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/Content.java
> +	public String ToJson() {
Respecter conventions SVP : BP Style

2019-03-20 07:40 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/dauphine_pole_info/TestJsonBDecode.java
> +	}
"test decode" doit tester uniquement le décodage : décoder le contenu à partir d’un fichier json et tester si l’objet obtenu est correct. Encoder-décoder ne documente pas le format attendu et ne permet pas de s’assurer pleinement que le format est respecté (il pourrait y avoir deux erreurs qui s’annulent).

2019-03-20 22:48 UTC, jannani-lahsen commented
@oliviercailloux  pouvez vous voir les modifications SVP. merci

2019-03-21 17:15 UTC, jannani-lahsen commented
J'ai supprimé les deux classes de test parce que les test de ces deux classes ne marchent plus vu que j'ai changé le format de la méthode  Tojson pour qu'il donne le resultat en "pretty print" alors qu'ils utilisent des test en dur dans un string 
exemple :  String str = "{\"id\":1,\"firstname\":\"Tuti\",\"lastname\":\"Dudi\",\"year_master\":0}";
String jsonExpected = "{\"studentPreference\":[{\"person\":\"{\\\"id\\\":1,\\\"firstname\\\":\\\"firstname\\\",\\\"lastname\\\":\\\"lastname\\\",\\\"year_master\\\":0}\"},[{\"preference\":\"{\\\"master\\\":{\\\"id\\\":1,\\\"name\\\":\\\"SITN\\\",\\\"description\\\":\\\"Description\\\"},\\\"level\\\":100}\"}]]}";
Est ce que je remet les deux classes et je mets les deux testes qui posent problème en commentaire ??

est ce que je peux faire deux pull request sur deux branches différentes en meme temps vu que j'ai deux fonctionnalités à faire ou je dois attendre la validation de la première ?

Merci beaucoup

2019-03-21 17:16 UTC, jannani-lahsen commented
Il faut faire avancer votre projet, pas faire un pas en avant et en même temps un pas en arrière.

Veuillez restaurer les deux tests et les modifier pour les adapter suite à vos changements, à moins que ce soit particulièrement compliqué, auquel cas, merci de m’expliquer pourquoi.

Je suis surpris, car il me semble que l’encodage des préférences est différent de l’encodage des objets de base, dont il me semble que votre fct s’occupe.

Oui, vous pouvez ouvrir deux PR en parallèle.

2019-03-21 17:47 UTC, oliviercailloux requested changes
Ok !

2019-03-21 17:47 UTC, oliviercailloux approved these changes

2019-03-21 17:48 UTC, oliviercailloux commented
(« requested changes » était une erreur, j’approuve)

2019-03-21 17:48 UTC, merged