Deployment
saraTag/Dauphine-Pole-Info pull request #20
Opened 2019-03-20 16:32 UTC by thejoker2323

2019-03-20 16:34 UTC, thejoker2323 commented
@oliviercailloux Comme discuté lors de la séance précédente , je m'occupérais à améliorer la partie déploiement automatique , de plus de l'intégration sur IBM Cloud.
Veuillez voir les changements apportés .

2019-03-21 17:42 UTC, oliviercailloux commented
Je ne vois pas grands changements ? Le déploiement était déjà configuré, sauf erreur de ma part, il fallait simplement changer le nom d’utilisateur. Veuillez d’ailleurs éviter de dupliquer tout et d’ajouter des commentaires, ça nuit à la lisibilité. Les changements apportés au manifest ne me semblent pas positifs, et l’ancien me semblait correct.

Nous avons discuté de l’intérêt de déployer auto sur IBM cloud l’ancienne application (PI3), la nouvelle, et vérifier que les deux communiquent. Ceci ne me semble pas avoir été fait.

2019-03-21 17:43 UTC, oliviercailloux requested changes
Cf. commentaire

2019-03-27 16:57 UTC, thejoker2323 commented
@oliviercailloux  j'ai corrigé les fichiers de config comme cela a été demandé , j'ai deployé aussi l'ancienne application PI3 , la nouvelle et je les ai liés à un méme service de base de données d'IBM Cloud (Db2) , cependant comme les changements n'ont pas affecté le code , je ne pourrais vous montré ce que j'ai fait qu'à la séance de demain 28/03.

2019-03-27 21:16 UTC, oliviercailloux commented
Il faut modifier les fichiers dans cette PR de façon à ce que ce déploiement soit reproductible automatiquement, pas manuel ; et introduire un ou plusieurs tests qui illustrent la communication.

2019-03-28 22:13 UTC, thejoker2323 commented
@oliviercailloux  j'ai documenté la démarche comme discuté tout à l'heure , et ajouté le schema de DB2.

2019-03-29 17:57 UTC, oliviercailloux approved these changes
Ok, moyennant restauration du nom précédent, qui me semblait bon. (Ou me préciser pourquoi ce changement est important.)

2019-03-29 17:57 UTC, oliviercailloux commented on manifest.yml
> + - name: Dauphine-Pole-Info-2019
Pourquoi 2019 ? Le nom précédent me semblait convenir.

2019-03-29 18:00 UTC, oliviercailloux commented
J’oubliais : préciser dans le document que l’application PI3 déployée sur ibm cloud avec ces instructions ne fonctionne pas.

2019-03-29 18:01 UTC, oliviercailloux commented
Pour l’itération suivante il faudra s’assurer 1) que vous arrivez à déployer PI3 sur votre machine et à le faire fonctionner, sinon, investiguer pourquoi ; 2) automatiser le déploiement sur IBM Cloud.

2019-03-29 18:10 UTC, thejoker2323 commented on manifest.yml
> + - name: Dauphine-Pole-Info-2019
ce changement est juste pour renommer l'application , car les noms étaient en conflicts lors des tests, et c'était une maniére pour contourner ce conflit , le nom définitif est celui :  - name: Dauphine-Pole-Info-2019

2019-03-29 18:10 UTC, merged