Link servlets
saraTag/Dauphine-Pole-Info pull request #21
Opened 2019-03-24 23:06 UTC by jannani-lahsen

Servlet permettant de récupérer, effacer, ajouter des liens entre master, cours et person, par id uniquement

2019-03-25 18:03 UTC, oliviercailloux requested changes
Voudriez-vous formater le code et indiquer là où c’est utile les raisons de vos choix (en javadoc) ? Par exemple, je ne comprends pas pourquoi utiliser un CourseId plutôt que des références vers le Contenu et le Master.
(Revue partielle, que je terminerai après plus d’information et formatage.)

2019-03-25 18:03 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/Content.java
> +	public Optional getDescription() {
Pourquoi pas String ici aussi, par cohérence ?

2019-03-25 18:03 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/Content.java
>  	public static void setJsonb(Jsonb jsonb) {
Je ne comprends pas pourquoi avoir enlevé certains Optional et en avoir ajouté d’autres. Il faut en tous cas utiliser Optional<> (le type générique), et non Optional. Respecter les warnings Eclipse (cf. Tools.adoc). Protéger vos String contre les null, BP null.

2019-03-26 11:49 UTC, jannani-lahsen commented
@oliviercailloux C'est fait, en effet j'ai utilisé le CourseID pour maper le clé primaire de Course qui est composé de id_master et id-contenu
Pour le Optional<> je l'avais changé, parce qu'il génère erreur could not determine type for java.util.optional avec hibernate que j'utilise comme provider dans ma persistence.xml pour tester les servlet en local qui ne le prend pas en charge comme montre le lien suivant : https://thoughts-on-java.org/use-java-8-optional-hibernate/

Merci

2019-03-27 21:04 UTC, oliviercailloux requested changes
Effacer CourseShort, à moins qu’il serve encore à quelque chose (auquel cas, documenter avec un TODO en vue de l’effacer, si ceci apparait comme une bonne idée).

Il aurait (beaucoup) mieux valu utiliser les mécanismes du conteneur et de JPA pour les transactions et les entity managers, mais on peut laisser ça pour une prochaine fct.

Bien que le travail réalisé soit utile, il ne me semble pas couvrir la fct annoncée. Comment ajouter des liens entre master, cours et person ? (Telle personne enseigne tel contenu dans tel master.)

Avez-vous testé extensivement votre code ? L’effacement d’une personne, par exemple, réagit-il correctement si la personne enseigne des cours ? (Et quelle est la réaction appropriée d’après vous ?)

2019-03-27 21:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/DeleteCourse.java
> +	public Response Delete() throws Exception {
Ne pas lancer une exception aussi générale.
Respecter conventions de nommage, BP Style.

2019-03-27 21:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/DeleteCourse.java
> +		return Response.ok("ok").build();
Ne pas renvoyer de réponse, laisser le conteneur faire, ce sera plus simple.

2019-03-27 21:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/DeletePersonByMaster.java
> +	static Logger log;
Enlever toutes ces variables log qui ne servent à rien.
Warnings Eclipse, cf. Tools.adoc.

2019-03-29 01:49 UTC, jannani-lahsen commented
@oliviercailloux J'ai fait le nettoyage du code nécessaire, ainsi que j'ai ajouté le add de linkservlet en plus des recuperations que j'avais fait avant.
Pour le Optional<> ca marche maintenant pour tous les testes sauf pour le test studentPreferenceToJson(), je l'ai mis en commentaire vu qu'il est marqué que c'est pas bon comme JSON et qu'il est à revoir, donc en le mettant en commentaire ca va pas reculer le projet en étant à la base incorrect
Pouvez vous revoir le code SVP 
merci

2019-03-29 17:34 UTC, oliviercailloux requested changes
Je ne vois toujours pas où se situe la réponse à la question de l’énoncé : liens entre master, contenu et person par id. Pourriez-vous me préciser où regarder ? (Votre commentaire parle de "link servlet", mais je ne vois pas de classe de ce nom.)

Les servlets ajoutés fonctionnent sur une base qui ne semble pas pertinente et qui devra être modifiée. Dès lors, en ajouter beaucoup d’autres qui posent le même problème ne me semble pas pertinent. (Considérons par exemple `GetcourseByContent`, mais les autres posent des problèmes du même type.) Ils n’utilisent pas les mécanismes du conteneur ni de JPA pour la gestion des transactions; pour l’injection de l’entity manager; ils s’exposent à de l’injection SQL plutôt qu’utiliser le mécanisme de création de requêtes SQL (ou JQL) vu au cours.

Par ailleurs, il y avait déjà un certain nombre de mécanismes dans le projet, par exemple AddPerson existait déjà.

Je vous suggère d’effacer la plupart de vos changements et d’introduire seulement un sous-ensemble de changements bien circonscris, dont vous êtes sûr de la qualité, et de m’expliquer quelle fct cela produit exactement, en vous concentrant en priorité sur les liens entre master, contenu et person par id.

2019-03-29 17:34 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +		<class>io.github.oliviercailloux.y2018.dauphine_pole_info.Content</class>
Non, ne pas lister toutes les entités manuellement ! Voir exemple du cours si nécessaire.

2019-03-29 17:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/GetPerson.java
> +	public List<Person> getAllPersons() throws NullPointerException {
Pourquoi annoncer que ceci envoie NullPointerException ?

2019-03-29 17:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/GetPersonByMaster.java
> +	@SuppressWarnings("unchecked")
Non, à éviter

2019-03-29 17:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/GetPersonByMaster.java
> +	public List<Person> getPersonByMaster(@QueryParam("master") int master) throws NullPointerException {
Comment le conteneur va-t-il pouvoir produire du texte utile à votre utilisateur à partir de cette liste de Person ?

2019-03-31 21:55 UTC, jannani-lahsen commented
@oliviercailloux  la fonctionalité likservlets : Servlet permettant de récupérer, effacer, ajouter des liens entre master, cours et person, par id uniquement

Pour l'ajout : veuillez voir SVP addPerson et addCourse
Pour la suppression veuillez voir SVP  DeleteCourseBuContent et DeleteCourseByMasteret DeletePersonByMaser
Pour la récupération veuillez voir SVP GetCourseByMaster et GetCourseByContent et GetPersonByMaster

Pour manipuler directement la base de données par défaut de wildfly veuillez voir svp la persisatance.xml

Merci

2019-04-01 08:20 UTC, oliviercailloux requested changes
Je continue à penser que vous devriez vous concentrer dans cette PR sur un plus petit nombre de nouvelles fonctionnalités, pour vous assurer qu’elles sont bien faites et fonctionnent bien (et pour minimiser le retard), et ensuite seulement (s’il reste du temps) étendre en appliquant la même logique sur d’autres servlets, ce qui sera nettement plus facile une fois que vous en aurez fournies quelques-unes de bonne qualité.

2019-04-01 08:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/AddPerson.java
> +		per.setTemporary(per.getTemporary());
Éviter cette liste d’appels. Pourquoi ne pas persister la personne originale, tout simplement ?

2019-04-01 08:20 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +    	<jta-data-source>java:jboss/datasources/ExampleDS</jta-data-source>
Ceci n’est pas la BD par défaut. Voir exemple du cours. Formater le fichier. Ajouter des propriétés pour déploiement automatique du schéma de la BD et autres propriétés utiles, voir exemple du cours.

2019-04-01 08:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/AddCourse.java
> +	@PersistenceContext(unitName = "dauphine")
Ne pas préciser partout le nom de l’unité, laisser par défaut.

2019-04-01 08:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/AddCourse.java
> +			@QueryParam("enseignat") int enseigant, @QueryParam("notes") String notes) {
Attention aux fautes de frappe SVP, sinon ce servlet sera inutilisable.

2019-04-01 08:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/AddCourse.java
> +
Il faut supposer qu’on vous envoie des ids de master, de contenu, et d’enseignant, qui existent déjà.
Il faut renommer la variable master en idMaster, et ainsi de suite, pour plus de clarté.
Il faut parler anglais : teacher, pas enseignant.

2019-04-01 08:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/Master.java
>  	/**
Veuillez retirer la méthode `setId`, pour éviter la tentation de l’utiliser. C’est JPA qui choisit l’id, pas l’utilisateur. Même chose sur autres entités.

2019-04-02 01:52 UTC, jannani-lahsen commented
@oliviercailloux j'ai pas enlevé les setId parce que je les utilises dans les classes addCourse et addPerson
Pouvez vous revoir les changement que j'ai fait

Merci

2019-04-02 07:24 UTC, oliviercailloux commented
> @oliviercailloux j'ai pas enlevé les setId parce que je les utilises dans les classes addCourse et addPerson

Justement, d’où ma remarque. J’insiste pour que vous enleviez les `setId` et corrigiez le reste du code de façon à ce qu’il ne choisisse pas les identifiants. C’est la BD qui doit le faire, pas l’utilisateur.

Je reverrai le code après ce changement.

2019-04-02 16:38 UTC, jannani-lahsen commented
@oliviercailloux  C'est fait

2019-04-03 20:33 UTC, oliviercailloux approved these changes

2019-04-03 20:37 UTC, merged