implement GUI Client to modify person ant content
saraTag/Dauphine-Pole-Info pull request #27
Opened 2019-04-01 17:17 UTC by saraTag

@oliviercailloux 
Lors du PR #25 (qui correspond à fonctionnalité pour le sprint 2 et les corrections d'exceptions), j'ai cru comprendre que vous m'avez demandé d'introduire un  PR prioritaire pour but juste de résoudre le problème de déploiement du serveur , j'ai dont créé un PR #26 mais si je comprends bien d'après votre commentaire sur ce dernier, je dois laisser mon camarade s'en occuper ,c'est pourquoi j'ai pourquoi j'ai créé ce PR qui ne prends en compte que ma fonctionnalité .

2019-04-01 21:20 UTC, oliviercailloux commented
Ma demande faisait suite à notre discussion en séance, où je vous demandais en tant qu’équipe de résoudre le problème, en discutant entre vous et en décidant qui s’en charge. Je pensais en écrivant ma remarque en PR #25 que vous aviez décidé ensemble que c’était vous. Mais en analysant la PR #21 entre-temps, il m’a semblé qu’elle résolvait la plupart des problèmes.

2019-04-01 21:20 UTC, oliviercailloux requested changes

2019-04-01 21:20 UTC, oliviercailloux commented on src/main/webapp/Content.html
> +	    alert(" modification validée")
Ne faudrait-il pas faire dépendre la confirmation du retour ? Il faut au moins avertir le client si le code retour envoyé par le servlet est un code d’erreur !

2019-04-01 21:20 UTC, oliviercailloux commented on src/main/webapp/Content.html
> +	    xmlHttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
Il faut envoyer l’info en json à votre servlet.

2019-04-02 14:16 UTC, saraTag commented
@oliviercailloux 
Voilà les modification que j'ai pu faire !

2019-04-02 14:27 UTC, oliviercailloux requested changes

2019-04-02 14:27 UTC, oliviercailloux commented on src/main/webapp/Content.html
> +<!------ Include the above in your HEAD tag ---------->
Ne faut-il pas alors inclure les lignes ci-dessus dans le HEAD, comme indiqué ?

2019-04-02 14:27 UTC, oliviercailloux commented on src/main/webapp/Content.html
> +	<meta name="author" content="">
Formater SVP.

2019-04-02 14:27 UTC, oliviercailloux commented on src/main/webapp/Content.html
> +	    data.push(document.getElementById('id_nom').value);
Heuuu c’est tout ? Y aurait-il une raison qui m’échapperait pour ne pas étendre aux autres champs ?

2019-04-02 17:36 UTC, saraTag commented on src/main/webapp/Content.html
> +<!------ Include the above in your HEAD tag ---------->
Corrigé !

2019-04-02 17:36 UTC, saraTag commented on src/main/webapp/Content.html
> +	<meta name="author" content="">
Corrigé!

2019-04-02 17:40 UTC, saraTag commented on src/main/webapp/Content.html
> +	    data.push(document.getElementById('id_nom').value);
@oliviercailloux 
C'est parce qu'il n'ya que deux paramètres au niveau de la servlet UpdateContent (id et nom) !

2019-04-03 20:34 UTC, oliviercailloux approved these changes

2019-04-03 20:52 UTC, merged