Feat/sprint3
saraTag/Dauphine-Pole-Info pull request #28
Opened 2019-04-02 15:08 UTC by saraTag

2019-04-02 17:44 UTC, saraTag commented
@oliviercailloux 
Voici les fonctionnalités qu'on propose pour l'itération 3

2019-04-03 20:41 UTC, oliviercailloux requested changes

2019-04-03 20:41 UTC, oliviercailloux commented on README.adoc
> +Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande de supprimer un Contenu et une Person.
Ça ne vaut pas un point de difficulté, sauf erreur de ma part, il suffit d’un bouton, d’un champ et d’un appel de servlet !

2019-04-03 20:41 UTC, oliviercailloux commented on README.adoc
> +Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande l'ajout de Contenu.
Même chose (et même chose ci-dessous), ça ne vaut pas un point de fct si c’est rudimentaire, à moins que je m’imagine mal ce que vous allez proposer.

Vous pouvez éventuellement travailler à deux sur un GUI non rudimentaire (qqch. de joli et un peu sophistiqué et agréable à utiliser, responsive), assez complet, pour deux voire trois pts de diff. (à partager).

Il reste aussi à consolider l’application : vérifier que l’intégration fonctionne bien avec PI3. Je suis sûr qu’il y a encore bcp de choses à corriger sur ce point de vue.

2019-04-03 21:02 UTC, saraTag commented on README.adoc
> +Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande l'ajout de Contenu.
@oliviercailloux 
Qu'est ce que c'est une GUI non rudimentaire du point de vue technique ? est ce que que ça sera des formulaires ? Pourrais-je avoir plus d'éclaircissement s'il vous plait ?
Merci

2019-04-04 07:34 UTC, oliviercailloux commented on README.adoc
> +Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande l'ajout de Contenu.
Pas JSP, plutôt HTML 5. Qqch. de joli et un peu sophistiqué et agréable à utiliser, responsive. Voir par exemple [ici](https://medium.com/level-up-web/top-free-responsive-html5-css3-website-templates-2018-edition-5b3fb3d96cc9).

J’insiste cependant sur la consolidation de l’application. Il serait peut-être plus adéquat de se contenter d’un GUI rudimentaire (sur le modèle déjà proposé de simples formulaires HTML) et de placer en contrepartie beaucoup d’efforts sur la consolidation de l’application. Il faut que ça tourne, à la fin.

Posez-moi la question de cours par e-mail SVP, pour ne pas encombrer la discussion sur cette PR. (Je ne la comprends pas, en l’état ; quelles manipulations exactement ?)

2019-04-06 18:00 UTC, closed without merging