add template and implement crud for Person
saraTag/Dauphine-Pole-Info pull request #31
Opened 2019-04-06 02:00 UTC by saraTag

@oliviercailloux 
J'ai ajouté un template dont la page principale est "index.html" ensuite  j'ai mis un lien vers la page "students.html" ou j'ai fais un crud .

2019-04-06 14:47 UTC, saraTag commented
@oliviercailloux 
Est ce que c'est trop tard pour la correction de ce PR ?

2019-04-06 15:46 UTC, oliviercailloux requested changes
Ok dans l’ensemble, qqs détails à modifier.

2019-04-06 15:46 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +      		<property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect" />
Ceci peut être une bonne idée, mais en l’occurrence à retirer car je préfère éviter des ennuis en cas de changement de BD.

2019-04-06 15:46 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +			<property name="hibernate.show_sql" value="true" />
Formater le code.

2019-04-06 15:46 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/UpdatePerson.java
> +	public Response Update(@QueryParam("id") int id, Person p) {
Conventions SVP. BP Style.

2019-04-06 15:46 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/AddPerson.java
> +		Person per = new Person(p.getFirstname(),p.getLastname(),p.getEmail(),p.getPhone(),p.getFax(),p.getMaster());
Il serait plus élégant d’implémenter un constructeur sur Person qui fait ça.

2019-04-06 15:46 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/AddPerson.java
> +	public Response Response (Person p) {
Changer ce nom de méthode.

2019-04-06 20:14 UTC, saraTag commented
@oliviercailloux 
je viens de corriger les erreurs !

2019-04-07 08:14 UTC, oliviercailloux requested changes

2019-04-07 08:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/DeletePerson.java
> +	@Consumes(MediaType.TEXT_PLAIN)
Ce n’est pas vrai.

2019-04-07 08:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/Person.java
> +		super();
Corriger le commentaire SVP, et remettre celui-ci au bon endroit. Décider et préciser dans la doc de ce que vous faites de l’id. Ne rien en faire sans rien dire n’est pas une bonne solution en tous cas.

2019-04-07 09:08 UTC, oliviercailloux approved these changes

2019-04-07 10:55 UTC, merged