Gui/master
saraTag/Dauphine-Pole-Info pull request #32
Opened 2019-04-06 16:15 UTC by jannani-lahsen

J'ai ajouté un template (disponible sur le lien suivant : https://www.tutorialrepublic.com/snippets/preview.php?topic=bootstrap&file=crud-data-table-for-database-with-modal-form) de crud pour manager l'objet matser, ainsi j'ai créé des fonction js pour la consommation des services add/update/delete pour l'objet master

2019-04-06 17:39 UTC, oliviercailloux requested changes
- Formater code.
- L’avez-vous testé ?
- Indiquer dans votre README la provenance de votre template !

2019-04-06 18:30 UTC, jannani-lahsen commented
@oliviercailloux c'est fait. Pour le test ca marche encore pas

2019-04-07 08:06 UTC, oliviercailloux commented
Lorsque vous intégrez du code d’autrui, il faut indiquer clairement que votre projet l’utilise. Par exemple, mentionner dans le README de votre projet la provenance de votre template html. Cette mention doit être claire, pas être noyée dans un flot de texte où vous décrivez d’autres choses. Veuillez déplacer la mention.

2019-04-07 08:06 UTC, oliviercailloux approved these changes

2019-04-07 08:08 UTC, oliviercailloux approved these changes
J’approuve moyennant les changements mineurs indiqués en commentaire, vous pouvez fusionner dès que c’est modifié.

2019-04-07 08:08 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/AddMaster.java
> +	@Produces(MediaType.TEXT_PLAIN)
Ce n’est pas vrai.

2019-04-07 08:08 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/dauphine_pole_info/UpdateMaster.java
> +    private EntityManager manager;
Code non formaté correctement.

2019-04-07 10:36 UTC, merged